/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectsr.view;

import com.projectsr.controller.ProjectController;
import com.projectsr.listener.ProjectListener;
import com.projectsr.model.ProjectModel;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hendri
 */
public class MainPanel extends javax.swing.JPanel implements ProjectListener {
    
    private ProjectModel model;
    private ProjectController controller;
    private JFileChooser fileChooser;
    private BufferedImage citraSatu;
    private BufferedImage citraDua;
    private Image temp;
    private File fileSatu;
    private File fileDua;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        
        model = new ProjectModel();
        controller = new ProjectController();
        
        model.setListener(this);
        controller.setModel(model);
        controller.setView(this);
        fileChooser = new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bluePanel1 = new com.widget.karisma.container.BluePanel();
        panelOval1 = new com.widget.karisma.container.PanelOval();
        panelLine1 = new com.widget.karisma.container.PanelLine();
        panelWhiteBorder2 = new com.widget.karisma.container.PanelWhiteBorder();
        buttonCheck = new com.widget.karisma.face.ButtonGlass();
        labelResult = new javax.swing.JLabel();
        panelOval2 = new com.widget.karisma.container.PanelOval();
        panelWhiteBorder1 = new com.widget.karisma.container.PanelWhiteBorder();
        panelOval3 = new com.widget.karisma.container.PanelOval();
        buttonOpenImg1 = new com.widget.karisma.face.ButtonGlass();
        panelOval5 = new com.widget.karisma.container.PanelOval();
        scrollImage1 = new javax.swing.JScrollPane();
        imageSatu = new javax.swing.JLabel();
        panelWhiteBorder3 = new com.widget.karisma.container.PanelWhiteBorder();
        panelOval4 = new com.widget.karisma.container.PanelOval();
        buttonOpenImg2 = new com.widget.karisma.face.ButtonGlass();
        panelOval6 = new com.widget.karisma.container.PanelOval();
        scrollImage2 = new javax.swing.JScrollPane();
        imageDua = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        bluePanel1.setLayout(new java.awt.BorderLayout());

        panelOval1.setLayout(new java.awt.BorderLayout());

        panelWhiteBorder2.setPreferredSize(new java.awt.Dimension(451, 108));

        buttonCheck.setText("Check Result");
        buttonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckActionPerformed(evt);
            }
        });

        labelResult.setForeground(new java.awt.Color(255, 255, 255));
        labelResult.setText("Match Result :");

        javax.swing.GroupLayout panelWhiteBorder2Layout = new javax.swing.GroupLayout(panelWhiteBorder2);
        panelWhiteBorder2.setLayout(panelWhiteBorder2Layout);
        panelWhiteBorder2Layout.setHorizontalGroup(
            panelWhiteBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWhiteBorder2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(buttonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelWhiteBorder2Layout.setVerticalGroup(
            panelWhiteBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWhiteBorder2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(panelWhiteBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        panelLine1.add(panelWhiteBorder2, java.awt.BorderLayout.CENTER);

        panelOval2.setPreferredSize(new java.awt.Dimension(651, 400));
        panelOval2.setLayout(new java.awt.GridLayout(1, 0));

        panelWhiteBorder1.setLayout(new java.awt.BorderLayout());

        panelOval3.setPreferredSize(new java.awt.Dimension(346, 45));

        buttonOpenImg1.setText("Open File Image 1");
        buttonOpenImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenImg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOval3Layout = new javax.swing.GroupLayout(panelOval3);
        panelOval3.setLayout(panelOval3Layout);
        panelOval3Layout.setHorizontalGroup(
            panelOval3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonOpenImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelOval3Layout.setVerticalGroup(
            panelOval3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOpenImg1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelWhiteBorder1.add(panelOval3, java.awt.BorderLayout.PAGE_END);

        imageSatu.setForeground(new java.awt.Color(255, 255, 255));
        imageSatu.setText("                          IMAGE SATU");
        scrollImage1.setViewportView(imageSatu);

        javax.swing.GroupLayout panelOval5Layout = new javax.swing.GroupLayout(panelOval5);
        panelOval5.setLayout(panelOval5Layout);
        panelOval5Layout.setHorizontalGroup(
            panelOval5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelOval5Layout.setVerticalGroup(
            panelOval5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOval5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(scrollImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelWhiteBorder1.add(panelOval5, java.awt.BorderLayout.LINE_START);

        panelOval2.add(panelWhiteBorder1);

        panelWhiteBorder3.setLayout(new java.awt.BorderLayout());

        panelOval4.setPreferredSize(new java.awt.Dimension(346, 45));

        buttonOpenImg2.setText("Open File Image 2");
        buttonOpenImg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenImg2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOval4Layout = new javax.swing.GroupLayout(panelOval4);
        panelOval4.setLayout(panelOval4Layout);
        panelOval4Layout.setHorizontalGroup(
            panelOval4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonOpenImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelOval4Layout.setVerticalGroup(
            panelOval4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonOpenImg2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelWhiteBorder3.add(panelOval4, java.awt.BorderLayout.PAGE_END);

        imageDua.setForeground(new java.awt.Color(255, 255, 255));
        imageDua.setText("                                IMAGE DUA");
        scrollImage2.setViewportView(imageDua);

        javax.swing.GroupLayout panelOval6Layout = new javax.swing.GroupLayout(panelOval6);
        panelOval6.setLayout(panelOval6Layout);
        panelOval6Layout.setHorizontalGroup(
            panelOval6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelOval6Layout.setVerticalGroup(
            panelOval6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOval6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(scrollImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelWhiteBorder3.add(panelOval6, java.awt.BorderLayout.PAGE_START);

        panelOval2.add(panelWhiteBorder3);

        panelLine1.add(panelOval2, java.awt.BorderLayout.PAGE_START);

        panelOval1.add(panelLine1, java.awt.BorderLayout.PAGE_END);

        bluePanel1.add(panelOval1, java.awt.BorderLayout.CENTER);

        add(bluePanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public BufferedImage getCitraSatu() {
        return citraSatu;
    }
    
    public BufferedImage getCitraDua() {
        return citraDua;
    }
    
    private void buttonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckActionPerformed
        // TODO add your handling code here:
        if (citraSatu == null) {
            JOptionPane.showMessageDialog(this, "Maaf anda belum memasukan image pertama..");
        } else if (citraDua == null) {
            JOptionPane.showMessageDialog(this, "Maaf anda belum memasukan image Dua..");
        } else {
            controller.runChecker();
        }
    }//GEN-LAST:event_buttonCheckActionPerformed
    
    private void buttonOpenImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenImg1ActionPerformed
        // TODO add your handling code here:
        int getRest = fileChooser.showOpenDialog(this);
        if (getRest == JFileChooser.APPROVE_OPTION) {
            try {
                citraSatu = ImageIO.read(new File(fileChooser.getSelectedFile().toURI()));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
//            temp = citraSatu.getScaledInstance(drawPanel1.getWidth(), drawPanel1.getHeight(), citraSatu.SCALE_FAST);
            imageSatu.setText("");
            imageSatu.setIcon(new ImageIcon(citraSatu));
//            drawPanel1.setImage(citraSatu, citraSatu.getHeight(), citraSatu.getWidth());
//            drawPanel1.repaint();

        }
        
    }//GEN-LAST:event_buttonOpenImg1ActionPerformed
    
    private void buttonOpenImg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenImg2ActionPerformed
        // TODO add your handling code here:
        int getRest = fileChooser.showOpenDialog(this);
        if (getRest == JFileChooser.APPROVE_OPTION) {
            try {
                citraDua = ImageIO.read(new File(fileChooser.getSelectedFile().toURI()));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            imageDua.setText("");
//            temp = citraDua.getScaledInstance(drawPanel1.getWidth(), drawPanel1.getHeight(), citraDua.SCALE_FAST);
            imageDua.setIcon(new ImageIcon(citraDua));
        }
    }//GEN-LAST:event_buttonOpenImg2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.widget.karisma.container.BluePanel bluePanel1;
    private com.widget.karisma.face.ButtonGlass buttonCheck;
    private com.widget.karisma.face.ButtonGlass buttonOpenImg1;
    private com.widget.karisma.face.ButtonGlass buttonOpenImg2;
    private javax.swing.JLabel imageDua;
    private javax.swing.JLabel imageSatu;
    private javax.swing.JLabel labelResult;
    private com.widget.karisma.container.PanelLine panelLine1;
    private com.widget.karisma.container.PanelOval panelOval1;
    private com.widget.karisma.container.PanelOval panelOval2;
    private com.widget.karisma.container.PanelOval panelOval3;
    private com.widget.karisma.container.PanelOval panelOval4;
    private com.widget.karisma.container.PanelOval panelOval5;
    private com.widget.karisma.container.PanelOval panelOval6;
    private com.widget.karisma.container.PanelWhiteBorder panelWhiteBorder1;
    private com.widget.karisma.container.PanelWhiteBorder panelWhiteBorder2;
    private com.widget.karisma.container.PanelWhiteBorder panelWhiteBorder3;
    private javax.swing.JScrollPane scrollImage1;
    private javax.swing.JScrollPane scrollImage2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void checkResult(Double result) {
        if (result != null) {
            DecimalFormat df = new DecimalFormat("####.##");
            
            labelResult.setText("Match Result : " + df.format(result).toString() + " %");
        } else {
            labelResult.setText("Match Result : Data tidak ada yang dibandingkan");
        }
        
    }
}
